### ISSUE TITLE
Synthesize survey data (when it comes in)

### ISSUE THREAD

**Issue by davemcorwin** [18F/doj-it-pa#59]

**Comment by Jacklynn** [comment]
I started a [sheet](https://docs.google.com/spreadsheets/d/1DX8juxVLTSGEm2fnZoTB-qR-nSyWK4vJPW5kyA0fwmU/edit#gid=1209325547) here to start thinking about how to structure the data when when it comes in, since we left it a free form text. 

...Based on the ways we might want to be able to organize the data (feel free to add things!):
- See how many time X service is brought up positively and negatively
- See what new services are brought up by participants
- See overlap between working and not working services
- Collect qualitative feedback in open-ended responses
- Compare services mentioned across 3 components
- See how many participants answered all questions
